### ISSUE TITLE
Laravel 8 support?

### ISSUE THREAD

**Issue by kylescousin** [messerli90/hunterio#1]
Any plans in upgrading for L8 support?

**Comment by messerli90** [comment]
Definitely. I should have some time this week to get to it. Otherwise feel free to create a PR

**Comment by stratocentric** [comment]
Any update on 8 support or how to install with 8?

**Comment by messerli90** [comment]
Laravel 8 support available with v2.0.0

https://github.com/messerli90/hunterio/releases/tag/2.0.0
